name: chat-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - alembic
  - pydantic
  - pydantic-settings
  - pip
  - pip:
      - ollama
      - python-multipart
      - PyJWT
